In [1]:
from sklearn.model_selection import train_test_split
from PIL import Image
import numpy as np
import os

import pickle

In [6]:
image_dir = os.getcwd() + '\\Train_Data_resized\\'
X = []
y = []


for image_path in os.listdir(os.fsencode(image_dir)):
    for image in os.listdir(os.fsencode(image_dir + str(image_path).replace("b'", '').replace("'", ''))):
        img_dir = os.fsencode(image_dir + str(image_path).replace("b'", '').replace("'", '') + '\\' + str(image).replace("b'", '').replace("'", ''))
        img = Image.open(img_dir)
        if img.size == (128,128):
            I = np.array(img.getdata(),
                    np.uint8).reshape(49152 , 1)
        #I = np.asarray(Image.open(img_dir))
            X.append(I.reshape(1, 49152))
            y.append(str(image_path).replace("b'", '').replace("'", ''))
            
        else:
            break
            
                 
                 




In [15]:
x = 0
for image_path in os.listdir(os.fsencode(image_dir)):
    for image in os.listdir(os.fsencode(image_dir + str(image_path).replace("b'", '').replace("'", ''))):
        img_dir = os.fsencode(image_dir + str(image_path).replace("b'", '').replace("'", '') + '\\' + str(image).replace("b'", '').replace("'", ''))
        img = Image.open(img_dir)
       
        if (img.size == (128,128)):
            x+=1
print(x)            

79


In [7]:
for i in range(0, len(X)):
    X[i] = X[i][0]

In [8]:
from sklearn.preprocessing import LabelEncoder

lb = LabelEncoder()

lb.fit(y)
y = lb.transform(y)

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [10]:
X_train

[array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 254, ..., 255, 255, 254], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([175, 190, 195, ..., 136, 141, 135], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([194, 183, 200, ..., 125, 114, 118], dtype=uint8),
 array([227, 243, 242, ..., 159, 173, 158], dtype=uint8),
 array([254, 254, 254, ..., 254, 254, 254], dtype=uint8),
 array([255, 255, 254, ..., 255, 255, 254], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([254, 254, 254, ..., 254, 254, 254], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 250], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 2

In [16]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

randf = RandomForestClassifier(n_estimators=600)

randf.fit(X_train, y_train)

pred = randf.predict(X_test)

acc_score = accuracy_score(y_test, pred)

print(acc_score)

  from numpy.core.umath_tests import inner1d


0.7083333333333334


In [17]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

randf = RandomForestClassifier(n_estimators=1500)

randf.fit(X_train, y_train)

pred = randf.predict(X_test)

acc_score = accuracy_score(y_test, pred)

print(acc_score)

0.7083333333333334


In [18]:
import pickle
import os


In [ ]:
pkl_filename = os.getcwd() + "\\sklearn_kct_model.pkl"  
with open(pkl_filename, 'wb') as file:  
    pickle.dump(randf, file)

from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X_train,y_train) 
y_pred = neigh.predict(X_test)



from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)

from sklearn import metrics

print(metrics.accuracy_score(y_test, y_pred))